# Generated by Django 2.1.5 on 2019-02-06 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applications',
            field=models.ManyToManyField(to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Приложения'),
        ),
    ]
