# Generated by Django 2.1.5 on 2019-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (3, 'customer')], primary_key=True, serialize=False),
        ),
    ]
