# Generated by Django 2.1.5 on 2019-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (3, 'customer')], primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
