# Generated by Django 2.1.5 on 2019-02-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190201_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Роль пользователья, от которого зависит привилегия пользователя', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Role', verbose_name='Роль'),
        ),
    ]
