# Generated by Django 2.1.5 on 2019-02-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190204_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(default=3, help_text='Роль пользователья в системе', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Администратор'), (2, 'Администратор приложения'), (3, 'Пользователь приложения')], primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
