# Generated by Django 2.1.5 on 2019-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_role_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scopes',
            field=models.TextField(choices=[('devices.view_device', 'Просмотр устройств'), ('devices.add_device', 'Добавление новых устройств'), ('devices.change_device', 'Изменение устройств'), ('devices.delete_device', 'Удаление устройств'), ('devices.view_device+devices.add_device', 'Просмотр/добавление устройств'), ('devices.view_device+devices.add_device+devices.change_device', 'Просмотр/добавление/изменение устройств'), ('devices.view_device+devices.add_device+devices.change_device+devices.delete_device', 'Управление устройствами')], default='read+write', verbose_name='Права доступа'),
        ),
    ]
