# Generated by Django 2.1.5 on 2019-02-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190206_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scopes',
            field=models.TextField(choices=[('read', 'чтение'), ('write', 'запись'), ('change', 'изменеие'), ('delete', 'удаление'), ('read+write', 'чтение/запись'), ('read+write+change', 'чтенеие/запись/измение'), ('read+write+change+delete', 'чтенеие/запись/измение/удаление'), ('devices.view_device', 'Просмотр устройств'), ('devices.add_device', 'Добавление новых устройств'), ('devices.change_device', 'Изменение устройств'), ('devices.delete_device', 'Удаление устройств'), ('devices.view_device+devices.add_device', 'Просмотр/добавление устройств'), ('devices.view_device+devices.add_device+devices.change_device', 'Просмотр/добавление/изменение устройств'), ('devices.view_device+devices.add_device+devices.change_device+devices.delete_device', 'Управление устройствами')], default='read+write', verbose_name='Права доступа'),
        ),
    ]
