# Generated by Django 2.1.5 on 2019-02-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190206_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='scopes',
            new_name='scope',
        ),
    ]
