# Generated by Django 2.1.7 on 2019-03-20 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='role',
            name='scope',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('read', 'чтение'), ('write', 'запись'), ('change', 'изменеие'), ('delete', 'удаление'), ('read+write', 'чтение/запись'), ('read+write+change', 'чтенеие/запись/измение'), ('read+write+change+delete', 'чтенеие/запись/измение/удаление'), ('devices.view_device', 'Просмотр устройств'), ('devices.add_device', 'Добавление новых устройств'), ('devices.change_device', 'Изменение устройств'), ('devices.delete_device', 'Удаление устройств'), ('devices.view_device+devices.add_device', 'Просмотр/добавление устройств'), ('devices.view_device+devices.add_device+devices.change_device', 'Просмотр/добавление/изменение устройств'), ('devices.view_device+devices.add_device+devices.change_device+devices.delete_device', 'Управление устройствами')], default='read+write', max_length=344, verbose_name='Права доступа в приложении'),
        ),
    ]
