# Generated by Django 2.1.7 on 2019-03-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactor',
            name='alive_period',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Время жизни кода, секунд'),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
    ]
